### ISSUE TITLE
Unable to connect to sdf.org

### ISSUE THREAD

**Issue by kbembedded** [jcs/msTERM#1]
In using the WiFiStation + msTERM I don't appear to be able to connect to sdf.org via telnet.

I can connect to klud.ge:23 either with `ATDS 1` (I've left the saved entries in WiFiStation default for now), as well as `ATDT klud.ge` but I don't appear to be able to readily connect to sdf.org:23

Running either `ATDT sdf.org` or `ATDT sdf.org:23` both result in the following output

```
DIALING sdf.org:23
CONNECT 115200 sdf.org:23
```

And it sits there indefinitely. Normally the telnet prompt from sdf is something like

```
sdf.org (pts/121)
if new, login 'new' ..

login:
```

I've not spent any time looking through TCP data, I'll do that when I have a chance, but wanted to open up an issue here to see if you've got any immediate insight.

msTERM built from the latest in git this this point in time.

**Comment by jcs** [comment]
Maybe the WiFiStation telnet negotiation is stuck.  If you issue `AT$NET=0` before connecting does it proceed?

**Comment by kbembedded** [comment]
That changes the behavior, but, still doesn't give a sane login prompt or respond to keypresses:

```
AT$NET=0
OK
ATDT sdf.org
DIALING sdf.org:23
CONNECT 115200 sdf.org:23
 ²%
```

That it, it looks like it prints out a superscript 2 and then a % symbol after a whitespace char. U+00B2 and U+0025

**Comment by jcs** [comment]
Yeah because it's not interpreting the IAC packets anymore but just printing them.  I'll try to debug it here with mine.

**Comment by jcs** [comment]
I believe this has been fixed in the WifiStation firmware if you want to issue an `AT$UPDATE` and try again.

**Comment by kbembedded** [comment]
Works like a charm now. Thanks!
